- name: install gitlab dependencies
  dnf:
    name: "{{ item }}"
    state: present

  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix

- name: install gitlab
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash && sudo dnf install gitlab-ce

- name: copy gitlab conf file
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
  notify: Reconfigure GitLab
